package lol.mifan.myblog.po;
// Generated 2017-5-16 12:53:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Power generated by hbm2java
 */
@Entity
@Table(name = "power", catalog = "mifanblog")
public class Power implements java.io.Serializable {

	private Integer id;
	private String name;
	private boolean deleted;
	private String note;
	private Set<Role> roles = new HashSet<Role>(0);

	public Power() {
	}

	public Power(boolean deleted) {
		this.deleted = deleted;
	}

	public Power(String name, boolean deleted, String note, Set<Role> roles) {
		this.name = name;
		this.deleted = deleted;
		this.note = note;
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "rolepower", catalog = "mifanblog", joinColumns = {
			@JoinColumn(name = "power_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
