package lol.mifan.myblog.po;
// Generated 2017-5-16 12:53:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag")
public class Tag implements java.io.Serializable {

	private Integer id;
	private String name;
	private boolean deleted;
	private String note;
	private Set<Article> articles = new HashSet<Article>(0);

	public Tag() {
	}

	public Tag(boolean deleted) {
		this.deleted = deleted;
	}

	public Tag(String name, boolean deleted, String note, Set<Article> articles) {
		this.name = name;
		this.deleted = deleted;
		this.note = note;
		this.articles = articles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "articletag", joinColumns = {
			@JoinColumn(name = "tag_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "article_id", nullable = false, updatable = false) })
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
